//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FunilMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CANDIDATOVAGA
    {
        public int CANID { get; set; }
        public int VAIID { get; set; }
        public System.DateTime CAVDATACADASTRO { get; set; }
        public string CAVSTATUSCANDIDATURA { get; set; }
    
        public virtual CANDIDATO CANDIDATO { get; set; }
        public virtual VAGA VAGA { get; set; }
    }
}
