//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FunilMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class GrupoCandidatoVaga
    {
        public int Codigo { get; set; }
        public string Nome { get; set; }
        public int CodigoV { get; set; }
        public string Vaga { get; set; }
        public System.DateTime DataDeCadastro { get; set; }
        public string Situacao { get; set; }
    }
}
