//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FunilMVC.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class BDFunilEntities1 : DbContext
    {
        public BDFunilEntities1()
            : base("name=BDFunilEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<CANDIDATO> CANDIDATO { get; set; }
        public virtual DbSet<CANDIDATOVAGA> CANDIDATOVAGA { get; set; }
        public virtual DbSet<ETAPA> ETAPA { get; set; }
        public virtual DbSet<VAGA> VAGA { get; set; }
        public virtual DbSet<GrupoCandidatoVaga> GrupoCandidatoVaga { get; set; }
        public virtual DbSet<DashBoard> DashBoard { get; set; }
    }
}
